-- Categorias
Insert into C##PRUEBA.CORE_CATEGORIA (IDCATEGORIA,NOMBRECATEGORIA,DETALLECATEGORIA,RUTAFOTO) values ('1','Correas','¡Es una nueva moda única para pasear perros! Muchos dueños de perros se pierden la maravillosa experiencia de llevar a su perro a pasear porque creen que a su perro no le gustará. La verdad es que a algunos perros les encanta caminar. Ya sea que lleve a su perro a dar un paseo por el vecindario, al veterinario o al peluquero, un arnés les da a nuestros perros la capacidad de explorar el mundo de manera segura.','https://i.postimg.cc/vT4R7D1Z/correa.png');
Insert into C##PRUEBA.CORE_CATEGORIA (IDCATEGORIA,NOMBRECATEGORIA,DETALLECATEGORIA,RUTAFOTO) values ('2','Placas','Disfruta de la tranquilidad de saber que en caso de emergencia su collar lleva tu contacto Pasea por tu barrio libremente, su collar posee un sistema de identificación para mascotas que proporciona a un smartphone con tecnología NFC la identidad de la mascota.','https://i.postimg.cc/ZKLg9rsx/placa.png');
Insert into C##PRUEBA.CORE_CATEGORIA (IDCATEGORIA,NOMBRECATEGORIA,DETALLECATEGORIA,RUTAFOTO) values ('3','Bandanas','¡Estas bandanas se convertirán en un artículo escencial para sus paseos! Disfruta de la gran variedad de diseños que poseemos para estar siempre a la moda con nuestros fieles compañeros. Para todos los tamaños, siempre a la moda.','https://i.postimg.cc/HsPwPnrC/bandana.png');
Insert into C##PRUEBA.CORE_CATEGORIA (IDCATEGORIA,NOMBRECATEGORIA,DETALLECATEGORIA,RUTAFOTO) values ('4','Comida para Gatos','Alimenta a tu felino regalón con la mejor comida de calidad para una larga vida saludable junto a él','https://i.postimg.cc/SND40F44/alimento-gato.png');
Insert into C##PRUEBA.CORE_CATEGORIA (IDCATEGORIA,NOMBRECATEGORIA,DETALLECATEGORIA,RUTAFOTO) values ('5','Comida para Perros','Elige lo mejor para tu mascota, con las necesidades nutricionales para su bienestar, un buen alimento concentrado debe estar compuesto por proteínas.','https://i.postimg.cc/y6jtxmbX/alimento-perro.jpg');
Insert into C##PRUEBA.CORE_CATEGORIA (IDCATEGORIA,NOMBRECATEGORIA,DETALLECATEGORIA,RUTAFOTO) values ('6','Comida para Ratas','Elige la mejor comida para tu pequeño amiguito!','https://i.postimg.cc/MHT7WPtv/image2.jpg');
-- Colores
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('0','No Aplica');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('1','Negro');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('2','Blanco');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('3','Azul');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('4','Rojo');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('5','Amarillo');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('6','Naranja');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('7','Rosa');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('8','Verde');	
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('9','Gris');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('10','Marrón');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('11','Turquesa');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('12','Verde Oliva');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('13','Verde Menta');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('14','Borgoña');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('15','Lavanda');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('16','Magenta');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('17','Salmón');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('18','Cian');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('19','Belge');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('20','Rosado');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('21','Verde Oscuro');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('22','Aceituna');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('23','Lila');
Insert into C##PRUEBA.CORE_COLORES (IDCOLOR,NOMBRECOLOR) values ('24','Amarillo Pálido');
-- Productos
Insert into C##PRUEBA.CORE_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,DETALLEPRODUCTO,CARACPRODUCTO,SKUPRODUCTO,STOCKPRODUCTO,COLORPRODUCTO_ID,RETIROTIENDA,DESPACHODOMICILIO,CATEGORIA_ID,IMGPRODUCTO,MICRODETALLEPRODUCTO) values ('1','Bandana Anhiz Ban53','5590','Bandana multifuncional con diseño con gran calidad de imagen, perfecta para realizar actividades deportivas o como un accesorio de moda. Se puede usar de diversas formas, como cuello, tapabocas, mascara, top, balaclava (con 2), cintillo, pirata, gorrito, muñequera, capucha, dona.','<ul> <li>Diseño tubular sin costuras</li>                             <li>Medidas: 50 x 25 cms</li>                             <li>Material: Jersey elasticado 100% Poliester</li>                             <li>De secado rápido.</li>                         </ul>','MPM00010258367','10','7','1','0','3','https://i.postimg.cc/HsPwPnrC/bandana.png','Bandana multifuncional con diseño con gran calidad de imagen.');
Insert into C##PRUEBA.CORE_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,DETALLEPRODUCTO,CARACPRODUCTO,SKUPRODUCTO,STOCKPRODUCTO,COLORPRODUCTO_ID,RETIROTIENDA,DESPACHODOMICILIO,CATEGORIA_ID,IMGPRODUCTO,MICRODETALLEPRODUCTO) values ('2','Placa Personalizada','15900','Placa identificadora para tu perro en aluminio anodizado y material anti-alérgico, se puede personalizar con 2 líneas en la parte posterior.','1 Línea: Nombre perro 2 Línea: Teléfono','MPM00010258365','20','17','1','0','2','https://i.postimg.cc/ZKLg9rsx/placa.png','PARA PERRO COLLAR CON COLGANTE CON PALABRAS TRAVIESAS Y LLAVERO');
Insert into C##PRUEBA.CORE_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,DETALLEPRODUCTO,CARACPRODUCTO,SKUPRODUCTO,STOCKPRODUCTO,COLORPRODUCTO_ID,RETIROTIENDA,DESPACHODOMICILIO,CATEGORIA_ID,IMGPRODUCTO,MICRODETALLEPRODUCTO) values ('3','CONJUNTO DE ARNÉS','10990','¡Es una nueva moda única para pasear perros! Muchos dueños de perros se pierden la maravillosa experiencia de llevar a su perro a pasear porque creen que a su perro no le gustará. La verdad es que a algunos perros les encanta caminar. Ya sea que lleve a su perro a dar un paseo por el vecindario, al veterinario o al peluquero, un arnés les da a nuestros perros la capacidad de explorar el mundo de manera segura.','El arnés en forma de H abraza a tu gato con seguridad para que no se suelte fácilmente. El producto está hecho de seda y dacrón, lo que lo hace suave y más duradero. La hebilla de liberación automática basada en POM permite una fijación firme así como una respuesta rápida a una situación de emergencia. De secado rápido.','MPM00010258364','44','19','0','1','1','https://i.postimg.cc/J0WfvXQ6/correa.jpg','¡Es una nueva moda única para pasear perros!');
Insert into C##PRUEBA.CORE_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,DETALLEPRODUCTO,CARACPRODUCTO,SKUPRODUCTO,STOCKPRODUCTO,COLORPRODUCTO_ID,RETIROTIENDA,DESPACHODOMICILIO,CATEGORIA_ID,IMGPRODUCTO,MICRODETALLEPRODUCTO) values ('4','ProPlan Sterilized','45390','Purina Pro Plan Sterilized Optirenal es la alimentación necesaria para Gatos cuando la esterilización o castración conduce a cambios hormonales que pueden afectar su metabolismo, aumentando la predisposición a un incremento de peso corporal, así como problemas urinarios.  Este alimento ha sido desarrollado por veterinarios y nutricionistas de Purina, ofreciendo una nutrición específica para gatos esterilizados y/o castrados promoviendo una salud óptima y bienestar general. La exclusiva tecnología patentada Optirenal es una mezcla de nutrientes, incluyendo antioxidantes, aminoácidos y ácidos grasos omega 3 y 6, que ayudan a mantener un funcionamiento renal óptimo.','Alimento para gatos Formulado para esterilizados o castrados Sabor a salmón con pollo','G1066','10','4','1','1','4','https://i.postimg.cc/NM8Jyz1D/proplan-sterilized-cat-75-kgs.jpg','Comida para Gatos Premium');
Insert into C##PRUEBA.CORE_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,DETALLEPRODUCTO,CARACPRODUCTO,SKUPRODUCTO,STOCKPRODUCTO,COLORPRODUCTO_ID,RETIROTIENDA,DESPACHODOMICILIO,CATEGORIA_ID,IMGPRODUCTO,MICRODETALLEPRODUCTO) values ('5','ProPlan Perro','38390','Pro Plan Exigent, en formato de 7,5 kgs., es un alimento para perros de razas pequeñas que ofrece una nutrición que dará un pelaje sano y brillante con un sabor único que los perros pequeños con paladares más exigentes disfrutarán. Este alimento ha sido formulado con VitaComplex-7, una combinación exclusiva de vitaminas, minerales y aminoácidos, además incluye selenio, beta-glucanos, antioxidantes vitales y vitaminas para estimular el sistema inmunológico, proporcionando un buen estado de salud general.  Pro Plan Exigent ha sido elaborado con proteína de alta calidad de carne fresca de pollo, con un sabor excepcionalmente atractivo, incluso para los perros más selectivos.','Alimento para perros con paladar exigente Para perros de razas pequeñas Formulado con pollo Con VitaComplet-7, minerales y antioxidantes Tamaño 7,5 Kilogramos','D1549','50','15','1','0','5','https://i.postimg.cc/3xCdcjC6/proplan-perro-exigent-raza-pequena-75-kgs.jpg','ProPlan Perro Exigent Raza Pequeña 7,5 Kgs');
Insert into C##PRUEBA.CORE_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,DETALLEPRODUCTO,CARACPRODUCTO,SKUPRODUCTO,STOCKPRODUCTO,COLORPRODUCTO_ID,RETIROTIENDA,DESPACHODOMICILIO,CATEGORIA_ID,IMGPRODUCTO,MICRODETALLEPRODUCTO) values ('6','Mazuri Ratas Y Raton','6990','Mazuri Rat & Mouse es un alimento para ratas y ratones de todas las edades y formulado con todos los nutrientes necesarios y específicos para ratas y ratones. Este alimento para ratas de Mazuri ha sido formulado en base a vegetales, contiene vitamina E y también linaza como fuente de ácidos grasos Omega 3. Además, la forma de su pellet facilita la alimentación y minimiza pérdida de comida.  Se recomienda dar ilimitado a ratas o ratones en crecimiento. En ratas adultas ofrecer 15 a 30 gramos al día, mientras que en ratones adultos es de 4 a 5 gramos por día. Siempre acompañar de heno ilimitado.','Alimento para ratas y ratones Para todas las edades Con linaza para un pelaje suave Con probióticos y vitaminas Recomendado por veterinarios Tamaño 900 gramos','123123','10','16','1','1','6','https://i.postimg.cc/k5Jy5vJ3/mazuri-ratas-y-ratones-900-grs.jpg','Mazuri Ratas Y Ratones 900 Grs comida para ratones');
-- Postulaciones
Insert into C##PRUEBA2.CORE_POSTULACION (IDPOSTULACION,NOMBRE,NUMERO,CORREO,ABOUT) values ('1','Juan Gabriel','+56969696969','juan@gabriel.com','Hola estoy interesado');
Insert into C##PRUEBA2.CORE_POSTULACION (IDPOSTULACION,NOMBRE,NUMERO,CORREO,ABOUT) values ('2','Rodolfo Reinaldo','+180004000','hola-s@ex.net','Hola quiero trabajar no tengo dinero para sustentar a mi familia, todos los dias me llaman del banco para cobrarme dinero que no tengo, estoy en dicom y no he pagado el arriendo en 3 meses, hoy me llegó la orden del juez para desalogo. ayuda porfavor');
Insert into C##PRUEBA2.CORE_POSTULACION (IDPOSTULACION,NOMBRE,NUMERO,CORREO,ABOUT) values ('3','Juan Colocolo','+56911111111','elmasgrande@colocolo.com','La verdad no estoy interesado, solo quería escribir GRANDE COLOCOLO');
Insert into C##PRUEBA2.CORE_POSTULACION (IDPOSTULACION,NOMBRE,NUMERO,CORREO,ABOUT) values ('4','Emilio Segundo','no tengo','no tengo','hol');