# Generated by Django 4.0.1 on 2022-05-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imgProducto',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL img'),
        ),
    ]
