# Generated by Django 4.0.1 on 2022-06-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_microdetalleproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('idColor', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Categoria')),
                ('nombreColor', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
        ),
    ]
