# Generated by Django 4.0.1 on 2022-06-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_colores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colores',
            name='idColor',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Color'),
        ),
        migrations.AlterField(
            model_name='colores',
            name='nombreColor',
            field=models.CharField(max_length=50, verbose_name='Nombre Color'),
        ),
    ]
