# Generated by Django 4.0.5 on 2022-06-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='categoria',
            name='detalleCategoria',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Detalle'),
        ),
    ]
