# Generated by Django 4.0.5 on 2022-06-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_usuario_categoria_detallecategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='rutaFoto',
            field=models.CharField(blank=True, max_length=150, verbose_name='RutaFoto'),
        ),
    ]
