# Generated by Django 4.0.5 on 2022-06-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categoria_rutafoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='rutaCategoria',
            field=models.CharField(blank=True, max_length=150, verbose_name='RutaCategoria'),
        ),
    ]
