# Generated by Django 4.0.1 on 2022-06-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categoria_rutacategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='rutaCategoria',
        ),
        migrations.AlterField(
            model_name='producto',
            name='colorProducto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.colores'),
            preserve_default=False,
        ),
    ]
