# Generated by Django 4.0.5 on 2022-06-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_categoria_rutacategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=150, verbose_name='Nombre de la Categoria'),
        ),
    ]
