# Generated by Django 4.0.5 on 2022-06-09 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_categoria_nombrecategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='colorProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.colores'),
        ),
    ]
