# Generated by Django 4.0.5 on 2022-06-09 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_producto_colorproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='colorProducto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.colores'),
            preserve_default=False,
        ),
    ]
