# Generated by Django 4.0.5 on 2022-06-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_producto_colorproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('idPostulacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Postulacion')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre Postulacion')),
                ('numero', models.CharField(max_length=15, verbose_name='Numero')),
                ('correo', models.CharField(max_length=300, verbose_name='Correo')),
                ('about', models.CharField(max_length=300, verbose_name='About')),
            ],
        ),
    ]
